"""Replace seasons with quarters, applications, wallets and usage ledger

Revision ID: fb7604f60412
Revises: 4a577dc82bd7
Create Date: 2026-10-01 08:55:21.214462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7604f60412'
down_revision: Union[str, Sequence[str], None] = '4a577dc82bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=False),
    sa.Column('application_opens_at', sa.Date(), nullable=True),
    sa.Column('application_closes_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'application_open', 'active', 'closed', name='quarterstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('subsidy_limit_krw', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarters_code'), 'quarters', ['code'], unique=True)
    op.create_table('personal_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_krw', sa.Integer(), nullable=False),
    sa.Column('consumed_krw', sa.Integer(), nullable=False),
    sa.Column('overage_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_balances_user_id'), 'personal_balances', ['user_id'], unique=True)
    op.create_table('personal_top_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_krw', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'rejected', 'cancelled', name='topupstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_top_ups_user_id'), 'personal_top_ups', ['user_id'], unique=False)
    op.create_table('quarter_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('build_percentage', sa.Integer(), nullable=False),
    sa.Column('video_percentage', sa.Integer(), nullable=False),
    sa.Column('requested_total_budget_krw', sa.Integer(), nullable=False),
    sa.Column('requested_build_budget_krw', sa.Integer(), nullable=False),
    sa.Column('requested_video_budget_krw', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'cancelled', name='applicationstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quarter_id', name='uq_application_user_quarter')
    )
    op.create_index(op.f('ix_quarter_applications_quarter_id'), 'quarter_applications', ['quarter_id'], unique=False)
    op.create_index(op.f('ix_quarter_applications_user_id'), 'quarter_applications', ['user_id'], unique=False)
    op.create_table('quarter_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('community_total_budget_krw', sa.Integer(), nullable=False),
    sa.Column('build_budget_krw', sa.Integer(), nullable=False),
    sa.Column('video_budget_krw', sa.Integer(), nullable=False),
    sa.Column('build_percentage', sa.Integer(), nullable=False),
    sa.Column('video_percentage', sa.Integer(), nullable=False),
    sa.Column('build_consumed_krw', sa.Integer(), nullable=False),
    sa.Column('video_consumed_krw', sa.Integer(), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['quarter_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quarter_id', name='uq_allocation_user_quarter')
    )
    op.create_index(op.f('ix_quarter_allocations_quarter_id'), 'quarter_allocations', ['quarter_id'], unique=False)
    op.create_index(op.f('ix_quarter_allocations_user_id'), 'quarter_allocations', ['user_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('build', 'video', name='budgetcategory', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('funding_source', sa.Enum('community_build', 'community_video', 'personal', name='fundingsource', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('provider_units', sa.Integer(), nullable=False),
    sa.Column('provider_unit', sa.String(length=20), nullable=False),
    sa.Column('provider_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('provider_currency', sa.String(length=10), nullable=False),
    sa.Column('charged_krw', sa.Integer(), nullable=False),
    sa.Column('builder_project_id', sa.Integer(), nullable=True),
    sa.Column('video_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_project_id'], ['builder_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_project_id'], ['video_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_quarter_id'), 'usage_events', ['quarter_id'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    # Children first: both reference seasons, so dropping the parent before
    # them fails on the foreign keys. Autogenerate emitted the wrong order.
    op.drop_index(op.f('ix_credit_allocations_season_id'), table_name='credit_allocations')
    op.drop_index(op.f('ix_credit_allocations_user_id'), table_name='credit_allocations')
    op.drop_table('credit_allocations')
    op.drop_index(op.f('ix_season_memberships_season_id'), table_name='season_memberships')
    op.drop_index(op.f('ix_season_memberships_user_id'), table_name='season_memberships')
    op.drop_table('season_memberships')
    op.drop_table('seasons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('allocated_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumed_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('credit_allocations_season_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credit_allocations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_allocations_pkey')),
    sa.UniqueConstraint('user_id', 'season_id', 'provider', 'resource_type', name=op.f('uq_allocation_scope'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_credit_allocations_user_id'), 'credit_allocations', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_allocations_season_id'), 'credit_allocations', ['season_id'], unique=False)
    op.create_table('season_memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'former'::character varying]::text[])", name=op.f('membershipstatus')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('season_memberships_season_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('season_memberships_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('season_memberships_pkey')),
    sa.UniqueConstraint('user_id', 'season_id', name=op.f('uq_membership_user_season'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_season_memberships_user_id'), 'season_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_season_memberships_season_id'), 'season_memberships', ['season_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('starts_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ends_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['upcoming'::character varying, 'active'::character varying, 'closed'::character varying]::text[])", name=op.f('seasonstatus')),
    sa.PrimaryKeyConstraint('id', name=op.f('seasons_pkey')),
    sa.UniqueConstraint('name', name=op.f('seasons_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_quarter_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_quarter_allocations_user_id'), table_name='quarter_allocations')
    op.drop_index(op.f('ix_quarter_allocations_quarter_id'), table_name='quarter_allocations')
    op.drop_table('quarter_allocations')
    op.drop_index(op.f('ix_quarter_applications_user_id'), table_name='quarter_applications')
    op.drop_index(op.f('ix_quarter_applications_quarter_id'), table_name='quarter_applications')
    op.drop_table('quarter_applications')
    op.drop_index(op.f('ix_personal_top_ups_user_id'), table_name='personal_top_ups')
    op.drop_table('personal_top_ups')
    op.drop_index(op.f('ix_personal_balances_user_id'), table_name='personal_balances')
    op.drop_table('personal_balances')
    op.drop_index(op.f('ix_quarters_code'), table_name='quarters')
    op.drop_table('quarters')
    # ### end Alembic commands ###
