"""phase 1b: per-quarter membership

Revision ID: fc206d3b9891
Revises: 6d2a45cc2666
Create Date: 2026-10-01 11:07:12.047799

Hand-edited after autogenerate: the reflected `sa.CheckConstraint` lines
were removed. The Enum column renders its own CHECK, so keeping the
reflected copies produces a duplicate that PostgreSQL rejects. This is
the behaviour documented in `app.db.base.status_enum`.

Adds the table only — no backfill. A member with no row is simply not
participating, so existing members correctly start as non-participants
until an admin approves their application or enrols them.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc206d3b9891'
down_revision: Union[str, Sequence[str], None] = '6d2a45cc2666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarter_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'former', name='membership_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quarter_id', name='uq_membership_user_quarter')
    )
    op.create_index(op.f('ix_quarter_memberships_quarter_id'), 'quarter_memberships', ['quarter_id'], unique=False)
    op.create_index(op.f('ix_quarter_memberships_user_id'), 'quarter_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarter_memberships_user_id'), table_name='quarter_memberships')
    op.drop_index(op.f('ix_quarter_memberships_quarter_id'), table_name='quarter_memberships')
    op.drop_table('quarter_memberships')
    # ### end Alembic commands ###
